/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.awt.Image;
import java.net.Socket;
import java.security.PrivateKey;
import java.security.PublicKey;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author acer main
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    Socket s;
    EnviarMsj em;
    String entradatext;
    Cifrado cifrado;
    Boolean pKey = false;
    PublicKey publicKey;
    PrivateKey privateKey;
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon image= new ImageIcon(getClass().getResource("/imag/dota.jpg"));
        ImageIcon icono = new ImageIcon(image.getImage().getScaledInstance(477,426,Image.SCALE_DEFAULT));
        never.setIcon(icono);
        entradatext= entrada.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        entrada = new javax.swing.JTextField();
        puertoEntrada = new javax.swing.JTextField();
        NombreEntrada = new javax.swing.JTextField();
        IpEntrada = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        puertoText = new javax.swing.JLabel();
        ipText = new javax.swing.JLabel();
        enviar = new javax.swing.JButton();
        desconectarBot = new javax.swing.JButton();
        conectarBot = new javax.swing.JButton();
        never = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setHorizontalScrollBar(null);

        chat.setEditable(false);
        chat.setColumns(10);
        chat.setLineWrap(true);
        chat.setRows(5);
        chat.setToolTipText("");
        chat.setWrapStyleWord(true);
        chat.setAutoscrolls(false);
        jScrollPane1.setViewportView(chat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 330, 180));

        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });
        entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entradaKeyPressed(evt);
            }
        });
        getContentPane().add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 330, 30));

        puertoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        puertoEntrada.setText("6000");
        getContentPane().add(puertoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, -1));

        NombreEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreEntrada.setText("User1");
        NombreEntrada.setToolTipText("");
        NombreEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(NombreEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, -1));

        IpEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IpEntrada.setText("localhost");
        IpEntrada.setToolTipText("");
        IpEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(IpEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 110, -1));

        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 20));

        puertoText.setForeground(new java.awt.Color(255, 255, 255));
        puertoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puertoText.setText("Puerto");
        getContentPane().add(puertoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 20));

        ipText.setForeground(new java.awt.Color(255, 255, 255));
        ipText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ipText.setText("IP");
        getContentPane().add(ipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 50, 20));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 70, 30));

        desconectarBot.setText("Desconectar");
        desconectarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desconectarBotActionPerformed(evt);
            }
        });
        getContentPane().add(desconectarBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, -1));

        conectarBot.setText("Conectar");
        conectarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarBotActionPerformed(evt);
            }
        });
        getContentPane().add(conectarBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 100, -1));

        never.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/dota.jpg"))); // NOI18N
        never.setMaximumSize(new java.awt.Dimension(850, 600));
        never.setMinimumSize(new java.awt.Dimension(850, 600));
        never.setPreferredSize(new java.awt.Dimension(850, 600));
        getContentPane().add(never, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaActionPerformed

    private void entradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==10){
            //System.out.println(entrada.getText());
            if(entrada.getText()!=entradatext){
            em.enviarMsj(NombreEntrada.getText()+": "+entrada.getText());
            entrada.setText(entradatext);
            }
        }
        
       // System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_entradaKeyPressed

    private void conectarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarBotActionPerformed
        // TODO add your handling code here:
        em=null;
        if(em==null){
            if(cifrado == null)
            {
                cifrado = new Cifrado();
            }
            em= new EnviarMsj(IpEntrada.getText(), Integer.parseInt(puertoEntrada.getText()),this);
            em.start();   
        }
        
    }//GEN-LAST:event_conectarBotActionPerformed

    private void IpEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpEntradaActionPerformed
   
    }//GEN-LAST:event_IpEntradaActionPerformed

    private void NombreEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEntradaActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        if(pKey == false)
        {
            if(cifrado.clavePublica != null){
            JOptionPane.showMessageDialog(null, "Voy a enviar llave");

            em.enviarLlave(cifrado.clavePublica);
            }
            
        }
        else if(entrada.getText()!= entradatext){
            em.enviarMsj(NombreEntrada.getText()+": "+entrada.getText());
            entrada.setText(entradatext);
            }
    }//GEN-LAST:event_enviarActionPerformed

    private void desconectarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desconectarBotActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_desconectarBotActionPerformed

    
    public void recibirMsj(String msj){
        String aux = cifrado.Descifrar(msj);
        chat.append(aux+ "\n");
        
    }
    
    public void recibirKey(PublicKey llavePublica){
        this.publicKey = llavePublica;
        pKey = true;
        JOptionPane.showMessageDialog(null, "Recibi llave");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IpEntrada;
    private javax.swing.JTextField NombreEntrada;
    private javax.swing.JTextArea chat;
    private javax.swing.JButton conectarBot;
    private javax.swing.JButton desconectarBot;
    private javax.swing.JTextField entrada;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel ipText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel never;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField puertoEntrada;
    private javax.swing.JLabel puertoText;
    // End of variables declaration//GEN-END:variables
}
